# Generated by Django 5.2.6 on 2025-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='estimated_time',
            field=models.PositiveIntegerField(help_text='Estimated time to complete the lesson in minutes', null=True),
        ),
    ]
