# Generated by Django 5.2.6 on 2025-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lesson_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete the lesson in minutes', null=True),
        ),
    ]
