# Generated by Django 5.2.6 on 2025-09-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
